name: 08:20 CET 

on:
  schedule:
    - cron: '20 09 * * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Ejecutar script
        run: node gym.js  
